# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


pod 'AFNetworking'
pod 'SDWebImage'

target 'Spider-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Spider-iOS


end

target 'Spider-Mac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Spider-Mac

end
